/*
 * Copyright 2013 ThirdMotion, Inc.
 *
 *	Licensed under the Apache License, Version 2.0 (the "License");
 *	you may not use this file except in compliance with the License.
 *	You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 *		Unless required by applicable law or agreed to in writing, software
 *		distributed under the License is distributed on an "AS IS" BASIS,
 *		WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *		See the License for the specific language governing permissions and
 *		limitations under the License.
 */

/*
 * @interface SimplifyIoC.Commands.ICommandBinding
 * 
 * Defines the form of a Binding for use with the CommandBinder. 
 * 
 * The only real distinctions between CommandBinding and Binding
 * are:
 * - the addition of `Once()`, which signals that the Binding should be destroyed immediately after a single use.
 * - a marker for running multiple commands in parallel (default) or sequentially.
 */

using System;
using SimplifyIoC.Framework;

namespace SimplifyIoC.Commands
{
    public interface ICommandBinding : IBinding
	{
		/// Declares that the Binding is a one-off. As soon as it's satisfied, it will be unmapped.
		ICommandBinding Once();

		/// Get/set the property set to `true` by `Once()`
		bool isOneOff{ get; set;}

		/// Declares that the bound commands will be run in parallel.
		/// Parallel is the default. There is no need to call this unless you're changing from sequence.
		ICommandBinding InParallel();

		/// Declares that the bound commands will be run as a sequence, rather than in parallel
		ICommandBinding InSequence ();

		/// Declares that the Commands generated by this binding will be pooled
		ICommandBinding Pooled();

		/// Get/set the property set by InSequence() and InParallel()
		bool isSequence{ get; set;}

		/// Get/set the property set by Pooled()
		bool isPooled{ get; set;}

		// ---- 4.3：信号直达处理器的短路通路 ----
		// 与 To<T>() / InSequence() / Pooled() 互斥，混用会在绑定期抛异常（早失败）。

		/// <summary>把信号直接绑到一个无载荷处理委托：Bind&lt;S&gt;().ToHandler&lt;TService&gt;(svc =&gt; svc.Do())</summary>
		ICommandBinding ToHandler<TService>(Action<TService> handler);

		/// <summary>一个信号载荷：ToHandler&lt;TService, T1&gt;((svc, v) =&gt; svc.Do(v))</summary>
		ICommandBinding ToHandler<TService, T1>(Action<TService, T1> handler);

		/// <summary>两个信号载荷</summary>
		ICommandBinding ToHandler<TService, T1, T2>(Action<TService, T1, T2> handler);

		/// <summary>三个信号载荷</summary>
		ICommandBinding ToHandler<TService, T1, T2, T3>(Action<TService, T1, T2, T3> handler);

		/// <summary>四个信号载荷（Signal 支持的上限）</summary>
		ICommandBinding ToHandler<TService, T1, T2, T3, T4>(Action<TService, T1, T2, T3, T4> handler);

		/// <summary>
		/// 弱类型兜底（逃生门）：载荷以 object[] 原样交给处理委托，不做个数/类型校验。
		/// 服务类型不可静态确定、或载荷形状多变时使用。
		/// </summary>
		ICommandBinding ToHandler<TService>(Action<TService, object[]> handler);

		new ICommandBinding Bind<T>();
		new ICommandBinding Bind(object key);
		new ICommandBinding To<T>();
		new ICommandBinding To(object o);
		new ICommandBinding ToName<T> ();
		new ICommandBinding ToName (object o);
		new ICommandBinding Named<T>();
		new ICommandBinding Named(object o);
	}
}

